# Generated by Django 5.2.9 on 2025-12-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('equipment', models.CharField(blank=True, default='', max_length=80)),
                ('is_dumbbell_pair', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Chest', 'Chest'), ('Triceps', 'Triceps'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders', 'Shoulders'), ('Traps', 'Traps')], max_length=32)),
                ('mood', models.CharField(choices=[('Exhausted', 'Exhausted'), ('Low Energy', 'Low Energy'), ('Normal', 'Normal'), ('Energetic', 'Energetic')], max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('weight_lb', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('quality', models.CharField(choices=[('bad', 'Bad'), ('ok', 'OK'), ('good', 'Good'), ('great', 'Great')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.workout')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
