# Generated by Django 5.2.9 on 2025-12-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='day',
            field=models.CharField(choices=[('Chest & Triceps', 'Chest & Triceps'), ('Back & Biceps', 'Back & Biceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], default='Core', max_length=32),
            preserve_default=False,
        ),
    ]
