# Generated by Django 5.2.9 on 2025-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_exercise_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], max_length=32),
        ),
    ]
