# Generated by Django 5.2.9 on 2026-01-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_workout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setentry',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.AddField(
            model_name='setentry',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps'), ('Combination', 'Combination')], max_length=32),
        ),
    ]
