# Generated by Django 5.2.9 on 2026-01-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_setentry_options_setentry_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='custom_exercise_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='setentry',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setentry',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='setentry',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], max_length=32),
        ),
    ]
