# Generated by Django 5.2.9 on 2026-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_add_custom_exercise_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='custom_equipment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
