# Generated by Django 5.2.9 on 2026-01-20 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_custom_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='distance_miles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='setentry',
            name='incline_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='setentry',
            name='speed_mph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workout',
            name='cardio_equipment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workout',
            name='cardio_type',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('rowing', 'Rowing'), ('elliptical', 'Elliptical'), ('stair_climber', 'Stair Climber'), ('jump_rope', 'Jump Rope'), ('walking', 'Walking'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workout',
            name='target_distance_miles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workout',
            name='target_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('weightlifting', 'Weightlifting'), ('cardio', 'Cardio'), ('hiit', 'HIIT')], default='weightlifting', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='HIITSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_intervals', models.PositiveIntegerField(default=8)),
                ('work_duration', models.PositiveIntegerField(default=30)),
                ('rest_duration', models.PositiveIntegerField(default=15)),
                ('intervals_completed', models.PositiveIntegerField(default=0)),
                ('total_work_time', models.PositiveIntegerField(default=0)),
                ('total_rest_time', models.PositiveIntegerField(default=0)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiit_session', to='tracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workout_type', models.CharField(choices=[('weightlifting', 'Weightlifting'), ('cardio', 'Cardio'), ('hiit', 'HIIT')], default='weightlifting', max_length=20)),
                ('day', models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardio_type', models.CharField(blank=True, choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('rowing', 'Rowing'), ('elliptical', 'Elliptical'), ('stair_climber', 'Stair Climber'), ('jump_rope', 'Jump Rope'), ('walking', 'Walking'), ('other', 'Other')], default='', max_length=32)),
                ('target_duration_minutes', models.PositiveIntegerField(default=0)),
                ('target_distance_miles', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hiit_intervals', models.PositiveIntegerField(default=8)),
                ('hiit_work_seconds', models.PositiveIntegerField(default=30)),
                ('hiit_rest_seconds', models.PositiveIntegerField(default=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_exercise_name', models.CharField(blank=True, default='', max_length=120)),
                ('custom_equipment', models.CharField(blank=True, default='', max_length=80)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps', models.PositiveIntegerField(default=10)),
                ('target_weight', models.PositiveIntegerField(default=0)),
                ('target_duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracker.workouttemplate')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('workout_type', models.CharField(choices=[('weightlifting', 'Weightlifting'), ('cardio', 'Cardio'), ('hiit', 'HIIT')], default='weightlifting', max_length=20)),
                ('day', models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps')], default='', max_length=32)),
                ('cardio_type', models.CharField(blank=True, choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('rowing', 'Rowing'), ('elliptical', 'Elliptical'), ('stair_climber', 'Stair Climber'), ('jump_rope', 'Jump Rope'), ('walking', 'Walking'), ('other', 'Other')], default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_from', to='tracker.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_workouts', to='tracker.workouttemplate')),
            ],
            options={
                'ordering': ['scheduled_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_from_template', to='tracker.workouttemplate'),
        ),
    ]
