# Generated by Django 5.2.9 on 2026-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_workout_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledworkout',
            name='day',
            field=models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps'), ('Other', 'Other')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps'), ('Other', 'Other')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='day',
            field=models.CharField(blank=True, choices=[('Custom Workout', 'Custom Workout'), ('Back & Biceps', 'Back & Biceps'), ('Chest & Triceps', 'Chest & Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Shoulders & Traps', 'Shoulders & Traps'), ('Other', 'Other')], default='', max_length=32),
        ),
    ]
