[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd web && python manage.py collectstatic --noinput"]

[start]
cmd = "bash start.sh"
